"""Outbound notifications (email / SMS) for resident one-time codes.

Pluggable: if a provider is configured via env (SendGrid for email, Twilio for SMS)
it is used; otherwise the message is logged so dev/UAT works without a provider.
The OTP itself is passed here only to be delivered — it is never persisted in
plaintext anywhere (only its hash is stored on the challenge).
"""
from __future__ import annotations

import logging

from app.core.config import settings

logger = logging.getLogger("casa-harmony.notify")


def _is_local_url(url: str) -> bool:
    return any(h in url for h in ("localhost", "127.0.0.1", "0.0.0.0"))


def link_base() -> str:
    """Base URL for links we email out, refusing an unusable one in production.

    A localhost base in production means every invite and reset link points at
    the recipient's own machine — a dead end they cannot diagnose or report. So
    the send is refused rather than completed silently.

    Raised as ValueError because app.main maps that to a 400: the admin who
    clicked "invite" gets told what is misconfigured, instead of a 500 or a
    cheerful success followed by a resident who cannot get in. Everything in the
    app that does not email a link keeps working regardless.
    """
    base = settings.FRONTEND_BASE_URL.rstrip("/")
    if settings.is_production and _is_local_url(base):
        raise ValueError(
            "FRONTEND_BASE_URL is not configured for this deployment, so the "
            "link in this email would point at the recipient's own machine. "
            "Set it to the public URL of the frontend and try again."
        )
    return base


def _suppressed(kind: str, to: str) -> bool:
    """True when the caller is a sandbox principal, so nothing is really sent.

    The sandbox exists so a developer can drive the real flows — resident
    invites, OTP challenges, password resets — without mail or SMS reaching an
    actual person. The message is logged instead, exactly as it is when no
    provider is configured, so the token/code is still recoverable from the log.
    """
    from app.core.context import get_context

    if not get_context().is_sandbox:
        return False
    logger.info("[SANDBOX] suppressed %s to %s (not sent)", kind, to)
    return True


def send_password_invite(to: str, token: str) -> None:
    """Email a one-time set-password link for a newly created account.

    ``token`` is a single-use password-reset token (bound to the password
    version), generated by the caller via :func:`create_password_reset_token`.
    Falls back to the dev log when no mail provider is configured.
    """
    link = f"{link_base()}/reset-password?token={token}"
    _send_email(
        to,
        "Welcome to Casa Harmony — set your password",
        f"Your account has been created. Use this link to set a password "
        f"(valid 30 minutes): {link}\n"
        "If you did not request this, ignore this email.",
    )


def send_resident_password_invite(to: str, hoa_slug: str, token: str) -> None:
    """Email a one-time set-password link for a newly invited resident.

    ``token`` is a single-use password-reset token (bound to the password
    version), generated by the caller via :func:`create_password_reset_token`.
    Mirrors :func:`send_password_invite` but points at the resident portal,
    which needs the HOA slug to sign the resident back in afterward.
    """
    link = f"{link_base()}/portal/accept-invite?hoa={hoa_slug}&token={token}"
    _send_email(
        to,
        "Welcome to Casa Harmony — set your password",
        f"Your resident account has been created. Use this link to set a password "
        f"(valid 30 minutes): {link}\n"
        "If you did not request this, ignore this email.",
    )


def _send_email(to: str, subject: str, body: str, attachments: list[tuple] | None = None) -> None:
    """Send an email. ``attachments`` is a list of (filename, bytes, mime_type).

    Whatever happens to it — really sent, suppressed for a sandbox caller, or
    logged for want of a provider — the message is also captured into the in-app
    inbox so invite links and codes can be read back without a real mailbox.
    """
    from app.models.dev_mailbox import (
        STATUS_FAILED, STATUS_NO_PROVIDER, STATUS_SENT, STATUS_SUPPRESSED,
    )
    from app.services.dev_mailbox import capture

    if _suppressed("email", to):
        logger.info("[SANDBOX] subject=%s body=%s", subject, body)
        capture(channel="EMAIL", to=to, subject=subject, body=body,
                status=STATUS_SUPPRESSED)
        return
    if settings.SENDGRID_API_KEY:
        try:
            import base64
            import httpx

            payload = {
                "personalizations": [{"to": [{"email": to}]}],
                "from": {"email": settings.MAIL_FROM},
                "subject": subject,
                "content": [{"type": "text/plain", "value": body}],
            }
            if attachments:
                payload["attachments"] = [
                    {"content": base64.b64encode(data).decode(), "filename": fn,
                     "type": mime, "disposition": "attachment"}
                    for fn, data, mime in attachments
                ]
            resp = httpx.post(
                "https://api.sendgrid.com/v3/mail/send",
                headers={"Authorization": f"Bearer {settings.SENDGRID_API_KEY}"},
                json=payload, timeout=12.0,
            )
            if resp.status_code >= 300:
                capture(channel="EMAIL", to=to, subject=subject, body=body,
                        status=STATUS_FAILED,
                        detail=f"SendGrid {resp.status_code}: {resp.text[:500]}")
            else:
                capture(channel="EMAIL", to=to, subject=subject, body=body,
                        status=STATUS_SENT)
            return
        except Exception as exc:  # pragma: no cover - provider/network issues
            logger.exception("SendGrid send failed; falling back to log")
            capture(channel="EMAIL", to=to, subject=subject, body=body,
                    status=STATUS_FAILED, detail=str(exc)[:500])
            return
    att = ", ".join(fn for fn, _, _ in (attachments or []))
    logger.info("[DEV EMAIL] to=%s subject=%s attachments=[%s] body=%s", to, subject, att, body)
    capture(channel="EMAIL", to=to, subject=subject, body=body,
            status=STATUS_NO_PROVIDER,
            detail=f"attachments: {att}" if att else None)


def _send_sms(to: str, body: str) -> None:
    from app.models.dev_mailbox import (
        STATUS_FAILED, STATUS_NO_PROVIDER, STATUS_SENT, STATUS_SUPPRESSED,
    )
    from app.services.dev_mailbox import capture

    if _suppressed("sms", to):
        logger.info("[SANDBOX] body=%s", body)
        capture(channel="SMS", to=to, subject=None, body=body,
                status=STATUS_SUPPRESSED)
        return
    if settings.TWILIO_ACCOUNT_SID and settings.TWILIO_AUTH_TOKEN:
        try:
            import httpx

            httpx.post(
                f"https://api.twilio.com/2010-04-01/Accounts/{settings.TWILIO_ACCOUNT_SID}/Messages.json",
                auth=(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN),
                data={"From": settings.TWILIO_FROM_NUMBER, "To": to, "Body": body},
                timeout=8.0,
            )
            capture(channel="SMS", to=to, subject=None, body=body, status=STATUS_SENT)
            return
        except Exception as exc:  # pragma: no cover
            logger.exception("Twilio send failed; falling back to log")
            capture(channel="SMS", to=to, subject=None, body=body,
                    status=STATUS_FAILED, detail=str(exc)[:500])
            return
    logger.info("[DEV SMS] to=%s body=%s", to, body)
    capture(channel="SMS", to=to, subject=None, body=body, status=STATUS_NO_PROVIDER)


def send_otp(channel: str, destination: str, code: str) -> None:
    body = (
        f"Your Casa Harmony verification code is {code}. "
        f"It expires in {settings.OTP_TTL_MINUTES} minutes. "
        "Do not share this code with anyone."
    )
    if channel == "SMS":
        _send_sms(destination, body)
    else:
        _send_email(destination, "Your Casa Harmony verification code", body)


# --- In-app notifications + budget-overrun alerts --------------------------
import uuid  # noqa: E402

from sqlalchemy import select  # noqa: E402
from sqlalchemy.orm import Session  # noqa: E402

from app.models.identity import Membership, Role, User  # noqa: E402
from app.models.notifications import Notification  # noqa: E402


def create_notification(
    db: Session, *, tenant_id: uuid.UUID, category: str, message: str,
    entity_type: str | None = None, entity_id: uuid.UUID | None = None,
    recipient_user_id: uuid.UUID | None = None, recipient_role_code: str | None = None,
) -> Notification:
    n = Notification(
        tenant_id=tenant_id, category=category, message=message,
        entity_type=entity_type, entity_id=entity_id,
        recipient_user_id=recipient_user_id, recipient_role_code=recipient_role_code,
    )
    db.add(n)
    db.flush()
    return n


def _users_with_role(db: Session, tenant_id: uuid.UUID, role_code: str) -> list[User]:
    return db.execute(
        select(User).join(Membership, Membership.user_id == User.id)
        .join(Role, Role.id == Membership.role_id)
        .where(Membership.tenant_id == tenant_id, Role.code == role_code)
    ).scalars().all()


def notify_budget_overrun(db: Session, *, tenant_id, invoice, po, staff_user_id=None) -> None:
    """Alert assigned staff (in-app) and the Board (in-app + best-effort email)."""
    msg = (
        f"Invoice {invoice.invoice_number} (${invoice.amount}) exceeds the limit on "
        f"PO {po.po_number} (cap ${po.amount_limit}, billed ${po.billed_amount}). "
        "Invoice placed on hold pending review."
    )
    create_notification(db, tenant_id=tenant_id, category="BUDGET_OVERRUN", message=msg,
                        entity_type="ApInvoice", entity_id=invoice.id,
                        recipient_role_code="BOARD_MEMBER")
    if staff_user_id:
        create_notification(db, tenant_id=tenant_id, category="BUDGET_OVERRUN", message=msg,
                            entity_type="ApInvoice", entity_id=invoice.id,
                            recipient_user_id=staff_user_id)
    for u in _users_with_role(db, tenant_id, "BOARD_MEMBER"):
        if u.email and not u.email.endswith("@anonymized.invalid"):
            _send_email(u.email, "Casa Harmony — PO budget overrun alert", msg)


def list_for_user(db: Session, tenant_id, user_id, role_codes, unread_only=False):
    conds = [Notification.recipient_user_id == user_id]
    if role_codes:
        conds.append(Notification.recipient_role_code.in_(list(role_codes)))
    stmt = select(Notification).where(
        Notification.tenant_id == tenant_id,
        (Notification.recipient_user_id == user_id)
        | (Notification.recipient_role_code.in_(list(role_codes)) if role_codes else False),
    )
    if unread_only:
        stmt = stmt.where(Notification.is_read.is_(False))
    return db.execute(stmt.order_by(Notification.created_at.desc())).scalars().all()


def mark_all_read(db: Session, tenant_id, user_id, role_codes):
    from sqlalchemy import update
    stmt = (
        update(Notification)
        .where(
            Notification.tenant_id == tenant_id,
            (Notification.recipient_user_id == user_id)
            | (Notification.recipient_role_code.in_(list(role_codes)) if role_codes else False),
            Notification.is_read.is_(False)
        )
        .values(is_read=True)
    )
    db.execute(stmt)
    db.flush()

