"""subledger, mfa secret, privacy, payments

Revision ID: 03284a5df438
Revises: a1b2c3d4e5f6
Create Date: 2026-06-20 03:29:50.311762
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.crypto_types


revision: str = '03284a5df438'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ar_homeowners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.String(length=40), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('property_unit', sa.String(length=40), nullable=True),
    sa.Column('bank_account', app.core.crypto_types.EncryptedString(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ar_homeowners_account_number'), 'ar_homeowners', ['account_number'], unique=False)
    op.create_index(op.f('ix_ar_homeowners_tenant_id'), 'ar_homeowners', ['tenant_id'], unique=False)
    op.create_table('data_subject_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('subject_user_id', sa.UUID(), nullable=True),
    sa.Column('subject_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_subject_requests_subject_user_id'), 'data_subject_requests', ['subject_user_id'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_tenant_id'), 'data_subject_requests', ['tenant_id'], unique=False)
    op.create_table('gl_journals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.UUID(), nullable=False),
    sa.Column('journal_number', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('accounting_date', sa.Date(), nullable=False),
    sa.Column('posted_at', sa.Date(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['structure_id'], ['kff_structures.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gl_journals_structure_id'), 'gl_journals', ['structure_id'], unique=False)
    op.create_index(op.f('ix_gl_journals_tenant_id'), 'gl_journals', ['tenant_id'], unique=False)
    op.create_table('ar_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('homeowner_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('gl_journal_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['gl_journal_id'], ['gl_journals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['homeowner_id'], ['ar_homeowners.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ar_invoices_homeowner_id'), 'ar_invoices', ['homeowner_id'], unique=False)
    op.create_index(op.f('ix_ar_invoices_tenant_id'), 'ar_invoices', ['tenant_id'], unique=False)
    op.create_table('gl_journal_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('code_combination_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['code_combination_id'], ['gl_code_combinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_id'], ['gl_journals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gl_journal_lines_journal_id'), 'gl_journal_lines', ['journal_id'], unique=False)
    op.create_index(op.f('ix_gl_journal_lines_tenant_id'), 'gl_journal_lines', ['tenant_id'], unique=False)
    op.add_column('users', sa.Column('mfa_secret', app.core.crypto_types.EncryptedString(length=255), nullable=True))
    # ### end Alembic commands ###

    # Row-Level Security for the new tenant-scoped tables (same predicate as the
    # base RLS migration). Grants for these tables are inherited via the
    # ALTER DEFAULT PRIVILEGES set in revision a1b2c3d4e5f6.
    predicate = (
        "current_setting('app.is_superadmin', true) = 'on' "
        "OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    )
    for table in (
        "data_subject_requests",
        "gl_journals",
        "gl_journal_lines",
        "ar_homeowners",
        "ar_invoices",
    ):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({predicate}) WITH CHECK ({predicate})"
        )


def downgrade() -> None:
    for table in (
        "ar_invoices",
        "ar_homeowners",
        "gl_journal_lines",
        "gl_journals",
        "data_subject_requests",
    ):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_secret')
    op.drop_index(op.f('ix_gl_journal_lines_tenant_id'), table_name='gl_journal_lines')
    op.drop_index(op.f('ix_gl_journal_lines_journal_id'), table_name='gl_journal_lines')
    op.drop_table('gl_journal_lines')
    op.drop_index(op.f('ix_ar_invoices_tenant_id'), table_name='ar_invoices')
    op.drop_index(op.f('ix_ar_invoices_homeowner_id'), table_name='ar_invoices')
    op.drop_table('ar_invoices')
    op.drop_index(op.f('ix_gl_journals_tenant_id'), table_name='gl_journals')
    op.drop_index(op.f('ix_gl_journals_structure_id'), table_name='gl_journals')
    op.drop_table('gl_journals')
    op.drop_index(op.f('ix_data_subject_requests_tenant_id'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_subject_user_id'), table_name='data_subject_requests')
    op.drop_table('data_subject_requests')
    op.drop_index(op.f('ix_ar_homeowners_tenant_id'), table_name='ar_homeowners')
    op.drop_index(op.f('ix_ar_homeowners_account_number'), table_name='ar_homeowners')
    op.drop_table('ar_homeowners')
    # ### end Alembic commands ###
