"""pdf attachment toggles and delivery attached flag

Revision ID: 0707b76bd5f2
Revises: 538242a9630f
Create Date: 2026-06-23 07:38:50.331761
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0707b76bd5f2'
down_revision: Union[str, None] = '538242a9630f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_config', sa.Column('attach_statement_pdf', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('scheduler_config', sa.Column('attach_board_pdf', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('statement_deliveries', sa.Column('attached', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statement_deliveries', 'attached')
    op.drop_column('scheduler_config', 'attach_board_pdf')
    op.drop_column('scheduler_config', 'attach_statement_pdf')
    # ### end Alembic commands ###
