"""compliance items

Revision ID: 0e09a81ef4d0
Revises: 2c4e8e43dfbe
Create Date: 2026-06-22 19:21:49.221772
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0e09a81ef4d0'
down_revision: Union[str, None] = '2c4e8e43dfbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_compliance_item_code')
    )
    op.create_index(op.f('ix_compliance_items_tenant_id'), 'compliance_items', ['tenant_id'], unique=False)
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; do NOT drop them.
    predicate = "current_setting('app.is_superadmin', true) = 'on' OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    op.execute('ALTER TABLE compliance_items ENABLE ROW LEVEL SECURITY')
    op.execute(
        f'CREATE POLICY tenant_isolation ON compliance_items '
        f'USING ({predicate}) WITH CHECK ({predicate})'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute('DROP POLICY IF EXISTS tenant_isolation ON compliance_items')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_items_tenant_id'), table_name='compliance_items')
    op.drop_table('compliance_items')
    # ### end Alembic commands ###
