"""cash management bank accounts statements

Revision ID: 168904d0f49c
Revises: 61e5e9562cdc
Create Date: 2026-06-22 12:18:32.054076
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.crypto_types


revision: str = '168904d0f49c'
down_revision: Union[str, None] = '61e5e9562cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ce_bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('account_number', app.core.crypto_types.EncryptedString(length=255), nullable=True),
    sa.Column('routing_number', sa.String(length=9), nullable=True),
    sa.Column('fund_value', sa.String(length=60), nullable=False),
    sa.Column('gl_cash_combination_id', sa.UUID(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['gl_cash_combination_id'], ['gl_code_combinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'account_code', name='uq_ce_account_code')
    )
    op.create_index(op.f('ix_ce_bank_accounts_tenant_id'), 'ce_bank_accounts', ['tenant_id'], unique=False)
    op.create_table('ce_statement_headers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ce_bank_account_id', sa.UUID(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reconciled_by', sa.UUID(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ce_bank_account_id'], ['ce_bank_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ce_statement_headers_ce_bank_account_id'), 'ce_statement_headers', ['ce_bank_account_id'], unique=False)
    op.create_index(op.f('ix_ce_statement_headers_tenant_id'), 'ce_statement_headers', ['tenant_id'], unique=False)
    op.create_table('ce_statement_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('header_id', sa.UUID(), nullable=False),
    sa.Column('line_num', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('line_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reconciled', sa.Boolean(), nullable=False),
    sa.Column('match_type', sa.String(length=12), nullable=True),
    sa.Column('matched_payment_id', sa.UUID(), nullable=True),
    sa.Column('matched_receipt_id', sa.UUID(), nullable=True),
    sa.Column('adjustment_je_header_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['ce_statement_headers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ce_statement_lines_header_id'), 'ce_statement_lines', ['header_id'], unique=False)
    op.create_index(op.f('ix_ce_statement_lines_tenant_id'), 'ce_statement_lines', ['tenant_id'], unique=False)
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; do NOT drop them.
    predicate = "current_setting('app.is_superadmin', true) = 'on' OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    for table in ('ce_bank_accounts', 'ce_statement_headers', 'ce_statement_lines'):
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON {table} '
            f'USING ({predicate}) WITH CHECK ({predicate})'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ('ce_bank_accounts', 'ce_statement_headers', 'ce_statement_lines'):
        op.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table}')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ce_statement_lines_tenant_id'), table_name='ce_statement_lines')
    op.drop_index(op.f('ix_ce_statement_lines_header_id'), table_name='ce_statement_lines')
    op.drop_table('ce_statement_lines')
    op.drop_index(op.f('ix_ce_statement_headers_tenant_id'), table_name='ce_statement_headers')
    op.drop_index(op.f('ix_ce_statement_headers_ce_bank_account_id'), table_name='ce_statement_headers')
    op.drop_table('ce_statement_headers')
    op.drop_index(op.f('ix_ce_bank_accounts_tenant_id'), table_name='ce_bank_accounts')
    op.drop_table('ce_bank_accounts')
    # ### end Alembic commands ###
