"""collections delinquency payment plans liens

Revision ID: 22933f00c427
Revises: efdfaa831b70
Create Date: 2026-06-23 00:14:05.922189
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '22933f00c427'
down_revision: Union[str, None] = 'efdfaa831b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delinquency_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('homeowner_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=False),
    sa.Column('balance_at_open', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'),
    sa.Column('last_notice_date', sa.Date(), nullable=True),
    sa.Column('notice_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['homeowner_id'], ['ar_homeowners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'homeowner_id', name='uq_delinquency_homeowner')
    )
    op.create_index(op.f('ix_delinquency_cases_homeowner_id'), 'delinquency_cases', ['homeowner_id'], unique=False)
    op.create_index(op.f('ix_delinquency_cases_tenant_id'), 'delinquency_cases', ['tenant_id'], unique=False)
    op.create_table('liens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lien_number', sa.String(length=40), nullable=False),
    sa.Column('homeowner_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=True),
    sa.Column('released_date', sa.Date(), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['homeowner_id'], ['ar_homeowners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'lien_number', name='uq_lien_number')
    )
    op.create_index(op.f('ix_liens_homeowner_id'), 'liens', ['homeowner_id'], unique=False)
    op.create_index(op.f('ix_liens_lien_number'), 'liens', ['lien_number'], unique=False)
    op.create_index(op.f('ix_liens_tenant_id'), 'liens', ['tenant_id'], unique=False)
    op.create_table('payment_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_number', sa.String(length=40), nullable=False),
    sa.Column('homeowner_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['homeowner_id'], ['ar_homeowners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'plan_number', name='uq_payment_plan_number')
    )
    op.create_index(op.f('ix_payment_plans_homeowner_id'), 'payment_plans', ['homeowner_id'], unique=False)
    op.create_index(op.f('ix_payment_plans_plan_number'), 'payment_plans', ['plan_number'], unique=False)
    op.create_index(op.f('ix_payment_plans_tenant_id'), 'payment_plans', ['tenant_id'], unique=False)
    op.create_table('payment_plan_installments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['payment_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_plan_installments_plan_id'), 'payment_plan_installments', ['plan_id'], unique=False)
    op.create_index(op.f('ix_payment_plan_installments_tenant_id'), 'payment_plan_installments', ['tenant_id'], unique=False)
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; do NOT drop them.
    predicate = "current_setting('app.is_superadmin', true) = 'on' OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    for table in ('delinquency_cases', 'payment_plans', 'payment_plan_installments', 'liens'):
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON {table} '
            f'USING ({predicate}) WITH CHECK ({predicate})'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ('delinquency_cases', 'payment_plans', 'payment_plan_installments', 'liens'):
        op.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table}')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_plan_installments_tenant_id'), table_name='payment_plan_installments')
    op.drop_index(op.f('ix_payment_plan_installments_plan_id'), table_name='payment_plan_installments')
    op.drop_table('payment_plan_installments')
    op.drop_index(op.f('ix_payment_plans_tenant_id'), table_name='payment_plans')
    op.drop_index(op.f('ix_payment_plans_plan_number'), table_name='payment_plans')
    op.drop_index(op.f('ix_payment_plans_homeowner_id'), table_name='payment_plans')
    op.drop_table('payment_plans')
    op.drop_index(op.f('ix_liens_tenant_id'), table_name='liens')
    op.drop_index(op.f('ix_liens_lien_number'), table_name='liens')
    op.drop_index(op.f('ix_liens_homeowner_id'), table_name='liens')
    op.drop_table('liens')
    op.drop_index(op.f('ix_delinquency_cases_tenant_id'), table_name='delinquency_cases')
    op.drop_index(op.f('ix_delinquency_cases_homeowner_id'), table_name='delinquency_cases')
    op.drop_table('delinquency_cases')
    # ### end Alembic commands ###
