"""ap config: payment terms, vendor types, distribution sets, 1099

Revision ID: 230ffec99c45
Revises: b019316ddbae
Create Date: 2026-06-21 22:36:00.496698
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '230ffec99c45'
down_revision: Union[str, None] = 'b019316ddbae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_distribution_set_name')
    )
    op.create_index(op.f('ix_distribution_sets_tenant_id'), 'distribution_sets', ['tenant_id'], unique=False)
    op.create_table('payment_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=True),
    sa.Column('due_days', sa.Integer(), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_payment_term_name')
    )
    op.create_index(op.f('ix_payment_terms_tenant_id'), 'payment_terms', ['tenant_id'], unique=False)
    op.create_table('vendor_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_vendor_type_code')
    )
    op.create_index(op.f('ix_vendor_types_tenant_id'), 'vendor_types', ['tenant_id'], unique=False)
    op.create_table('distribution_set_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('distribution_set_id', sa.UUID(), nullable=False),
    sa.Column('line_num', sa.Integer(), nullable=False),
    sa.Column('code_combination_id', sa.UUID(), nullable=False),
    sa.Column('percent', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('fund_value', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['code_combination_id'], ['gl_code_combinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['distribution_set_id'], ['distribution_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('distribution_set_id', 'line_num', name='uq_dist_set_line_num')
    )
    op.create_index(op.f('ix_distribution_set_lines_distribution_set_id'), 'distribution_set_lines', ['distribution_set_id'], unique=False)
    op.create_index(op.f('ix_distribution_set_lines_tenant_id'), 'distribution_set_lines', ['tenant_id'], unique=False)
    op.add_column('ap_invoices', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('ap_suppliers', sa.Column('payment_term_id', sa.UUID(), nullable=True))
    op.add_column('ap_suppliers', sa.Column('vendor_type_id', sa.UUID(), nullable=True))
    op.add_column('ap_suppliers', sa.Column('is_1099', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('ap_suppliers', sa.Column('income_tax_type', sa.String(length=20), nullable=True))
    op.add_column('ap_suppliers', sa.Column('state_reportable', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('ap_suppliers', sa.Column('tax_reporting_name', sa.String(length=200), nullable=True))
    op.create_foreign_key('fk_supplier_vendor_type', 'ap_suppliers', 'vendor_types', ['vendor_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_supplier_payment_term', 'ap_suppliers', 'payment_terms', ['payment_term_id'], ['id'], ondelete='SET NULL')
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; do NOT drop them.

    # RLS for the new tenant-scoped tables.
    predicate = (
        "current_setting('app.is_superadmin', true) = 'on' "
        "OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    )
    for table in ("payment_terms", "vendor_types", "distribution_sets", "distribution_set_lines"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({predicate}) WITH CHECK ({predicate})"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ("distribution_set_lines", "distribution_sets", "vendor_types", "payment_terms"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    op.drop_constraint('fk_supplier_payment_term', 'ap_suppliers', type_='foreignkey')
    op.drop_constraint('fk_supplier_vendor_type', 'ap_suppliers', type_='foreignkey')
    op.drop_column('ap_suppliers', 'tax_reporting_name')
    op.drop_column('ap_suppliers', 'state_reportable')
    op.drop_column('ap_suppliers', 'income_tax_type')
    op.drop_column('ap_suppliers', 'is_1099')
    op.drop_column('ap_suppliers', 'vendor_type_id')
    op.drop_column('ap_suppliers', 'payment_term_id')
    op.drop_column('ap_invoices', 'due_date')
    op.drop_index(op.f('ix_distribution_set_lines_tenant_id'), table_name='distribution_set_lines')
    op.drop_index(op.f('ix_distribution_set_lines_distribution_set_id'), table_name='distribution_set_lines')
    op.drop_table('distribution_set_lines')
    op.drop_index(op.f('ix_vendor_types_tenant_id'), table_name='vendor_types')
    op.drop_table('vendor_types')
    op.drop_index(op.f('ix_payment_terms_tenant_id'), table_name='payment_terms')
    op.drop_table('payment_terms')
    op.drop_index(op.f('ix_distribution_sets_tenant_id'), table_name='distribution_sets')
    op.drop_table('distribution_sets')
    # ### end Alembic commands ###
