"""resident mfa otp

Revision ID: 232abeec7d72
Revises: 85a50392782c
Create Date: 2026-06-20 15:07:24.815453
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '232abeec7d72'
down_revision: Union[str, None] = '85a50392782c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resident_otp_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('destination_masked', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resident_otp_challenges_resident_id'), 'resident_otp_challenges', ['resident_id'], unique=False)
    op.create_index(op.f('ix_resident_otp_challenges_tenant_id'), 'resident_otp_challenges', ['tenant_id'], unique=False)
    # server_default backfills existing residents (MFA on, email channel).
    op.add_column('residents', sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('residents', sa.Column('mfa_channel', sa.String(length=10), nullable=False, server_default='EMAIL'))
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; autogenerate
    # mis-flags them as removable. Do NOT drop them.

    predicate = (
        "current_setting('app.is_superadmin', true) = 'on' "
        "OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    )
    op.execute("ALTER TABLE resident_otp_challenges ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON resident_otp_challenges "
        f"USING ({predicate}) WITH CHECK ({predicate})"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON resident_otp_challenges")
    op.drop_column('residents', 'mfa_channel')
    op.drop_column('residents', 'mfa_enabled')
    op.drop_index(op.f('ix_resident_otp_challenges_tenant_id'), table_name='resident_otp_challenges')
    op.drop_index(op.f('ix_resident_otp_challenges_resident_id'), table_name='resident_otp_challenges')
    op.drop_table('resident_otp_challenges')
    # ### end Alembic commands ###
