"""ap payments methods schedules links

Revision ID: 24a0ec0aefc9
Revises: 4e2a74f79bc8
Create Date: 2026-06-21 23:40:35.623288
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '24a0ec0aefc9'
down_revision: Union[str, None] = '4e2a74f79bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ap_payment_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('method_type', sa.String(length=10), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['ap_bank_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_payment_method_code')
    )
    op.create_index(op.f('ix_ap_payment_methods_tenant_id'), 'ap_payment_methods', ['tenant_id'], unique=False)
    op.create_table('ap_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_number', sa.String(length=40), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('payment_method_id', sa.UUID(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.Column('memo', sa.String(length=240), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('gl_je_header_id', sa.UUID(), nullable=True),
    sa.Column('void_je_header_id', sa.UUID(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['ap_payment_methods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['ap_suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'payment_number', name='uq_payment_number')
    )
    op.create_index(op.f('ix_ap_payments_payment_number'), 'ap_payments', ['payment_number'], unique=False)
    op.create_index(op.f('ix_ap_payments_tenant_id'), 'ap_payments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ap_payments_vendor_id'), 'ap_payments', ['vendor_id'], unique=False)
    op.create_table('ap_invoice_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['ap_invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['ap_payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ap_invoice_payments_invoice_id'), 'ap_invoice_payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_ap_invoice_payments_payment_id'), 'ap_invoice_payments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_ap_invoice_payments_tenant_id'), 'ap_invoice_payments', ['tenant_id'], unique=False)
    op.create_table('ap_payment_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['ap_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ap_payment_schedules_invoice_id'), 'ap_payment_schedules', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_ap_payment_schedules_tenant_id'), 'ap_payment_schedules', ['tenant_id'], unique=False)
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; do NOT drop them.

    predicate = (
        "current_setting('app.is_superadmin', true) = 'on' "
        "OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    )
    for table in ("ap_payment_methods", "ap_payment_schedules", "ap_payments", "ap_invoice_payments"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({predicate}) WITH CHECK ({predicate})"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ("ap_payment_methods", "ap_payment_schedules", "ap_payments", "ap_invoice_payments"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    op.drop_index(op.f('ix_ap_payment_schedules_tenant_id'), table_name='ap_payment_schedules')
    op.drop_index(op.f('ix_ap_payment_schedules_invoice_id'), table_name='ap_payment_schedules')
    op.drop_table('ap_payment_schedules')
    op.drop_index(op.f('ix_ap_invoice_payments_tenant_id'), table_name='ap_invoice_payments')
    op.drop_index(op.f('ix_ap_invoice_payments_payment_id'), table_name='ap_invoice_payments')
    op.drop_index(op.f('ix_ap_invoice_payments_invoice_id'), table_name='ap_invoice_payments')
    op.drop_table('ap_invoice_payments')
    op.drop_index(op.f('ix_ap_payments_vendor_id'), table_name='ap_payments')
    op.drop_index(op.f('ix_ap_payments_tenant_id'), table_name='ap_payments')
    op.drop_index(op.f('ix_ap_payments_payment_number'), table_name='ap_payments')
    op.drop_table('ap_payments')
    op.drop_index(op.f('ix_ap_payment_methods_tenant_id'), table_name='ap_payment_methods')
    op.drop_table('ap_payment_methods')
    # ### end Alembic commands ###
