"""fixed assets and reserve studies

Revision ID: 2c4e8e43dfbe
Revises: f472d9cbb2bb
Create Date: 2026-06-22 19:13:24.160988
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2c4e8e43dfbe'
down_revision: Union[str, None] = 'f472d9cbb2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserve_studies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('study_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reserve_studies_tenant_id'), 'reserve_studies', ['tenant_id'], unique=False)
    op.create_table('fa_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_number', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('fund_value', sa.String(length=60), nullable=False),
    sa.Column('cost_center_value', sa.String(length=60), nullable=True),
    sa.Column('asset_combination_id', sa.UUID(), nullable=False),
    sa.Column('accum_depr_combination_id', sa.UUID(), nullable=True),
    sa.Column('depr_expense_combination_id', sa.UUID(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('salvage_value', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'),
    sa.Column('in_service_date', sa.Date(), nullable=False),
    sa.Column('life_months', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('disposal_date', sa.Date(), nullable=True),
    sa.Column('disposal_proceeds', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['accum_depr_combination_id'], ['gl_code_combinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_combination_id'], ['gl_code_combinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['depr_expense_combination_id'], ['gl_code_combinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'asset_number', name='uq_fa_asset_number')
    )
    op.create_index(op.f('ix_fa_assets_asset_number'), 'fa_assets', ['asset_number'], unique=False)
    op.create_index(op.f('ix_fa_assets_tenant_id'), 'fa_assets', ['tenant_id'], unique=False)
    op.create_table('fa_depreciation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('period_name', sa.String(length=15), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_num', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('je_header_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['fa_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'period_name', name='uq_fa_depr_period')
    )
    op.create_index(op.f('ix_fa_depreciation_asset_id'), 'fa_depreciation', ['asset_id'], unique=False)
    op.create_index(op.f('ix_fa_depreciation_tenant_id'), 'fa_depreciation', ['tenant_id'], unique=False)
    op.create_table('reserve_components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('fund_value', sa.String(length=60), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('useful_life_years', sa.Integer(), nullable=True),
    sa.Column('remaining_life_years', sa.Integer(), nullable=True),
    sa.Column('replacement_cost', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'),
    sa.Column('planned_year', sa.Integer(), nullable=True),
    sa.Column('planned_amount', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['fa_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['study_id'], ['reserve_studies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reserve_components_study_id'), 'reserve_components', ['study_id'], unique=False)
    op.create_index(op.f('ix_reserve_components_tenant_id'), 'reserve_components', ['tenant_id'], unique=False)
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; do NOT drop them.
    predicate = "current_setting('app.is_superadmin', true) = 'on' OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    for table in ('fa_assets', 'fa_depreciation', 'reserve_studies', 'reserve_components'):
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON {table} '
            f'USING ({predicate}) WITH CHECK ({predicate})'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ('fa_assets', 'fa_depreciation', 'reserve_studies', 'reserve_components'):
        op.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table}')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reserve_components_tenant_id'), table_name='reserve_components')
    op.drop_index(op.f('ix_reserve_components_study_id'), table_name='reserve_components')
    op.drop_table('reserve_components')
    op.drop_index(op.f('ix_fa_depreciation_tenant_id'), table_name='fa_depreciation')
    op.drop_index(op.f('ix_fa_depreciation_asset_id'), table_name='fa_depreciation')
    op.drop_table('fa_depreciation')
    op.drop_index(op.f('ix_fa_assets_tenant_id'), table_name='fa_assets')
    op.drop_index(op.f('ix_fa_assets_asset_number'), table_name='fa_assets')
    op.drop_table('fa_assets')
    op.drop_index(op.f('ix_reserve_studies_tenant_id'), table_name='reserve_studies')
    op.drop_table('reserve_studies')
    # ### end Alembic commands ###
