"""scheduler config and job runs

Revision ID: 3d01dda00a70
Revises: f8181bb3a884
Create Date: 2026-06-23 00:58:50.346665
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d01dda00a70'
down_revision: Union[str, None] = 'f8181bb3a884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_job_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.String(length=40), nullable=False),
    sa.Column('trigger', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_job_runs_job_name'), 'scheduled_job_runs', ['job_name'], unique=False)
    op.create_index(op.f('ix_scheduled_job_runs_tenant_id'), 'scheduled_job_runs', ['tenant_id'], unique=False)
    op.create_table('scheduler_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monthly_statements_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('board_packet_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('day_of_month', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_config_tenant_id'), 'scheduler_config', ['tenant_id'], unique=False)
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; do NOT drop them.
    predicate = "current_setting('app.is_superadmin', true) = 'on' OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    for table in ('scheduler_config', 'scheduled_job_runs'):
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON {table} '
            f'USING ({predicate}) WITH CHECK ({predicate})'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ('scheduler_config', 'scheduled_job_runs'):
        op.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table}')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduler_config_tenant_id'), table_name='scheduler_config')
    op.drop_table('scheduler_config')
    op.drop_index(op.f('ix_scheduled_job_runs_tenant_id'), table_name='scheduled_job_runs')
    op.drop_index(op.f('ix_scheduled_job_runs_job_name'), table_name='scheduled_job_runs')
    op.drop_table('scheduled_job_runs')
    # ### end Alembic commands ###
