"""tenant_monthly_dues_kind

Revision ID: 3d9c0ff90050
Revises: d0d87e7cfe34
Create Date: 2026-08-14 13:18:26.934846
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d9c0ff90050'
down_revision: Union[str, None] = 'd0d87e7cfe34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('monthly_dues', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('tenants', sa.Column('kind', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'kind')
    op.drop_column('tenants', 'monthly_dues')
    # ### end Alembic commands ###
