"""supplier sites contacts bank accounts + defaults

Revision ID: 4e2a74f79bc8
Revises: 230ffec99c45
Create Date: 2026-06-21 23:05:29.691429
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.crypto_types


revision: str = '4e2a74f79bc8'
down_revision: Union[str, None] = '230ffec99c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ap_supplier_bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=False),
    sa.Column('routing_number', sa.String(length=9), nullable=True),
    sa.Column('account_number', app.core.crypto_types.EncryptedString(length=255), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['ap_suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ap_supplier_bank_accounts_supplier_id'), 'ap_supplier_bank_accounts', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_ap_supplier_bank_accounts_tenant_id'), 'ap_supplier_bank_accounts', ['tenant_id'], unique=False)
    op.create_table('ap_supplier_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('site_code', sa.String(length=40), nullable=False),
    sa.Column('site_name', sa.String(length=120), nullable=True),
    sa.Column('pay_site', sa.Boolean(), nullable=False),
    sa.Column('purchasing_site', sa.Boolean(), nullable=False),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('payment_term_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['payment_term_id'], ['payment_terms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['ap_suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'supplier_id', 'site_code', name='uq_supplier_site_code')
    )
    op.create_index(op.f('ix_ap_supplier_sites_supplier_id'), 'ap_supplier_sites', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_ap_supplier_sites_tenant_id'), 'ap_supplier_sites', ['tenant_id'], unique=False)
    op.create_table('ap_supplier_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['ap_supplier_sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['ap_suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ap_supplier_contacts_supplier_id'), 'ap_supplier_contacts', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_ap_supplier_contacts_tenant_id'), 'ap_supplier_contacts', ['tenant_id'], unique=False)
    op.add_column('ap_suppliers', sa.Column('default_distribution_set_id', sa.UUID(), nullable=True))
    op.add_column('ap_suppliers', sa.Column('default_expense_combination_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_supplier_default_distset', 'ap_suppliers', 'distribution_sets', ['default_distribution_set_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_supplier_default_expense', 'ap_suppliers', 'gl_code_combinations', ['default_expense_combination_id'], ['id'], ondelete='SET NULL')
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; do NOT drop them.

    predicate = (
        "current_setting('app.is_superadmin', true) = 'on' "
        "OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    )
    for table in ("ap_supplier_sites", "ap_supplier_contacts", "ap_supplier_bank_accounts"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({predicate}) WITH CHECK ({predicate})"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ("ap_supplier_sites", "ap_supplier_contacts", "ap_supplier_bank_accounts"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    op.drop_constraint('fk_supplier_default_expense', 'ap_suppliers', type_='foreignkey')
    op.drop_constraint('fk_supplier_default_distset', 'ap_suppliers', type_='foreignkey')
    op.drop_column('ap_suppliers', 'default_expense_combination_id')
    op.drop_column('ap_suppliers', 'default_distribution_set_id')
    op.drop_index(op.f('ix_ap_supplier_contacts_tenant_id'), table_name='ap_supplier_contacts')
    op.drop_index(op.f('ix_ap_supplier_contacts_supplier_id'), table_name='ap_supplier_contacts')
    op.drop_table('ap_supplier_contacts')
    op.drop_index(op.f('ix_ap_supplier_sites_tenant_id'), table_name='ap_supplier_sites')
    op.drop_index(op.f('ix_ap_supplier_sites_supplier_id'), table_name='ap_supplier_sites')
    op.drop_table('ap_supplier_sites')
    op.drop_index(op.f('ix_ap_supplier_bank_accounts_tenant_id'), table_name='ap_supplier_bank_accounts')
    op.drop_index(op.f('ix_ap_supplier_bank_accounts_supplier_id'), table_name='ap_supplier_bank_accounts')
    op.drop_table('ap_supplier_bank_accounts')
    # ### end Alembic commands ###
