"""payment gateway config and transactions

Revision ID: 538242a9630f
Revises: 3d01dda00a70
Create Date: 2026-06-23 01:07:12.148198
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.crypto_types


revision: str = '538242a9630f'
down_revision: Union[str, None] = '3d01dda00a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateway_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('publishable_key', sa.String(length=255), nullable=True),
    sa.Column('secret_key', app.core.crypto_types.EncryptedString(length=255), nullable=True),
    sa.Column('webhook_secret', app.core.crypto_types.EncryptedString(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gateway_configs_tenant_id'), 'gateway_configs', ['tenant_id'], unique=False)
    op.create_table('gateway_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('txn_ref', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('homeowner_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=True),
    sa.Column('refund_of_id', sa.UUID(), nullable=True),
    sa.Column('gl_je_header_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['homeowner_id'], ['ar_homeowners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['ar_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gateway_transactions_homeowner_id'), 'gateway_transactions', ['homeowner_id'], unique=False)
    op.create_index(op.f('ix_gateway_transactions_tenant_id'), 'gateway_transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_gateway_transactions_txn_ref'), 'gateway_transactions', ['txn_ref'], unique=False)
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; do NOT drop them.
    predicate = "current_setting('app.is_superadmin', true) = 'on' OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    for table in ('gateway_configs', 'gateway_transactions'):
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON {table} '
            f'USING ({predicate}) WITH CHECK ({predicate})'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ('gateway_configs', 'gateway_transactions'):
        op.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table}')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gateway_transactions_txn_ref'), table_name='gateway_transactions')
    op.drop_index(op.f('ix_gateway_transactions_tenant_id'), table_name='gateway_transactions')
    op.drop_index(op.f('ix_gateway_transactions_homeowner_id'), table_name='gateway_transactions')
    op.drop_table('gateway_transactions')
    op.drop_index(op.f('ix_gateway_configs_tenant_id'), table_name='gateway_configs')
    op.drop_table('gateway_configs')
    # ### end Alembic commands ###
