"""receiving rcv headers lines transactions

Revision ID: 61e5e9562cdc
Revises: 8fbf7cf73a9b
Create Date: 2026-06-22 12:04:52.935157
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '61e5e9562cdc'
down_revision: Union[str, None] = '8fbf7cf73a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rcv_shipment_headers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt_number', sa.String(length=40), nullable=False),
    sa.Column('po_header_id', sa.UUID(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('packing_slip', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('needs_inspection', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('inspected_by', sa.UUID(), nullable=True),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['po_header_id'], ['po_headers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'receipt_number', name='uq_rcv_receipt_number')
    )
    op.create_index(op.f('ix_rcv_shipment_headers_po_header_id'), 'rcv_shipment_headers', ['po_header_id'], unique=False)
    op.create_index(op.f('ix_rcv_shipment_headers_receipt_number'), 'rcv_shipment_headers', ['receipt_number'], unique=False)
    op.create_index(op.f('ix_rcv_shipment_headers_tenant_id'), 'rcv_shipment_headers', ['tenant_id'], unique=False)
    op.create_table('rcv_shipment_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('header_id', sa.UUID(), nullable=False),
    sa.Column('line_num', sa.Integer(), nullable=False),
    sa.Column('po_line_id', sa.UUID(), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount_received', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['rcv_shipment_headers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_lines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rcv_shipment_lines_header_id'), 'rcv_shipment_lines', ['header_id'], unique=False)
    op.create_index(op.f('ix_rcv_shipment_lines_po_line_id'), 'rcv_shipment_lines', ['po_line_id'], unique=False)
    op.create_index(op.f('ix_rcv_shipment_lines_tenant_id'), 'rcv_shipment_lines', ['tenant_id'], unique=False)
    op.create_table('rcv_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_line_id', sa.UUID(), nullable=False),
    sa.Column('po_distribution_id', sa.UUID(), nullable=False),
    sa.Column('txn_type', sa.String(length=12), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fund_value', sa.String(length=60), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['po_distribution_id'], ['po_distributions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipment_line_id'], ['rcv_shipment_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rcv_transactions_po_distribution_id'), 'rcv_transactions', ['po_distribution_id'], unique=False)
    op.create_index(op.f('ix_rcv_transactions_shipment_line_id'), 'rcv_transactions', ['shipment_line_id'], unique=False)
    op.create_index(op.f('ix_rcv_transactions_tenant_id'), 'rcv_transactions', ['tenant_id'], unique=False)
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; do NOT drop them.
    predicate = (
        "current_setting('app.is_superadmin', true) = 'on' OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    )
    for table in ('rcv_shipment_headers', 'rcv_shipment_lines', 'rcv_transactions'):
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON {table} '
            f'USING ({predicate}) WITH CHECK ({predicate})'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ('rcv_shipment_headers', 'rcv_shipment_lines', 'rcv_transactions'):
        op.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table}')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rcv_transactions_tenant_id'), table_name='rcv_transactions')
    op.drop_index(op.f('ix_rcv_transactions_shipment_line_id'), table_name='rcv_transactions')
    op.drop_index(op.f('ix_rcv_transactions_po_distribution_id'), table_name='rcv_transactions')
    op.drop_table('rcv_transactions')
    op.drop_index(op.f('ix_rcv_shipment_lines_tenant_id'), table_name='rcv_shipment_lines')
    op.drop_index(op.f('ix_rcv_shipment_lines_po_line_id'), table_name='rcv_shipment_lines')
    op.drop_index(op.f('ix_rcv_shipment_lines_header_id'), table_name='rcv_shipment_lines')
    op.drop_table('rcv_shipment_lines')
    op.drop_index(op.f('ix_rcv_shipment_headers_tenant_id'), table_name='rcv_shipment_headers')
    op.drop_index(op.f('ix_rcv_shipment_headers_receipt_number'), table_name='rcv_shipment_headers')
    op.drop_index(op.f('ix_rcv_shipment_headers_po_header_id'), table_name='rcv_shipment_headers')
    op.drop_table('rcv_shipment_headers')
    # ### end Alembic commands ###
