"""go live status and backup runs

Revision ID: 754239dd12bf
Revises: 0e09a81ef4d0
Create Date: 2026-06-22 19:43:50.613953
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '754239dd12bf'
down_revision: Union[str, None] = '0e09a81ef4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_runs_tenant_id'), 'backup_runs', ['tenant_id'], unique=False)
    op.create_table('go_live_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('went_live_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('went_live_by', sa.UUID(), nullable=True),
    sa.Column('last_validation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_validation_passed', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_go_live_status_tenant_id'), 'go_live_status', ['tenant_id'], unique=False)
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; do NOT drop them.
    predicate = "current_setting('app.is_superadmin', true) = 'on' OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    for table in ('go_live_status', 'backup_runs'):
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON {table} '
            f'USING ({predicate}) WITH CHECK ({predicate})'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ('go_live_status', 'backup_runs'):
        op.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table}')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_go_live_status_tenant_id'), table_name='go_live_status')
    op.drop_table('go_live_status')
    op.drop_index(op.f('ix_backup_runs_tenant_id'), table_name='backup_runs')
    op.drop_table('backup_runs')
    # ### end Alembic commands ###
