"""po contract timeframe limit and qty tracking

Revision ID: 782a717dbb64
Revises: feb391f7b096
Create Date: 2026-06-22 00:03:21.619067
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '782a717dbb64'
down_revision: Union[str, None] = 'feb391f7b096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('po_distributions', sa.Column('quantity_ordered', sa.Numeric(precision=18, scale=4), nullable=False, server_default='0'))
    op.add_column('po_distributions', sa.Column('quantity_received', sa.Numeric(precision=18, scale=4), nullable=False, server_default='0'))
    op.add_column('po_distributions', sa.Column('quantity_billed', sa.Numeric(precision=18, scale=4), nullable=False, server_default='0'))
    op.add_column('po_distributions', sa.Column('amount_billed', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'))
    op.add_column('po_headers', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('po_headers', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('po_headers', sa.Column('amount_limit', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'))
    op.add_column('po_headers', sa.Column('billed_amount', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('po_headers', 'billed_amount')
    op.drop_column('po_headers', 'amount_limit')
    op.drop_column('po_headers', 'end_date')
    op.drop_column('po_headers', 'start_date')
    op.drop_column('po_distributions', 'amount_billed')
    op.drop_column('po_distributions', 'quantity_billed')
    op.drop_column('po_distributions', 'quantity_received')
    op.drop_column('po_distributions', 'quantity_ordered')
    # ### end Alembic commands ###
