"""ar accounting fields + gl budgets

Revision ID: 7a4ca8e99a04
Revises: d7b1f0c2a9e1
Create Date: 2026-06-20 13:10:24.553209
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7a4ca8e99a04'
down_revision: Union[str, None] = 'd7b1f0c2a9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gl_budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_name', sa.String(length=60), nullable=False),
    sa.Column('code_combination_id', sa.UUID(), nullable=False),
    sa.Column('period_name', sa.String(length=15), nullable=False),
    sa.Column('fund_value', sa.String(length=60), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['code_combination_id'], ['gl_code_combinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code_combination_id', 'period_name', name='uq_budget')
    )
    op.create_index(op.f('ix_gl_budgets_code_combination_id'), 'gl_budgets', ['code_combination_id'], unique=False)
    op.create_index(op.f('ix_gl_budgets_fund_value'), 'gl_budgets', ['fund_value'], unique=False)
    op.create_index(op.f('ix_gl_budgets_tenant_id'), 'gl_budgets', ['tenant_id'], unique=False)
    # AR invoice accounting fields (server_default backfills existing rows).
    op.add_column('ar_invoices', sa.Column('fund', sa.String(length=60), nullable=False, server_default='OPER'))
    op.add_column('ar_invoices', sa.Column('income_combination_id', sa.UUID(), nullable=True))
    op.add_column('ar_invoices', sa.Column('gl_je_header_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_ar_invoice_income_cc', 'ar_invoices', 'gl_code_combinations',
                          ['income_combination_id'], ['id'], ondelete='SET NULL')
    # NOTE: the performance indexes from revision d7b1f0c2a9e1 are intentionally
    # retained — they exist only in migrations (not the ORM models), so autogenerate
    # mis-detects them as removable. Do not drop them here.

    # RLS for the new tenant-scoped budgets table.
    predicate = (
        "current_setting('app.is_superadmin', true) = 'on' "
        "OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    )
    op.execute("ALTER TABLE gl_budgets ENABLE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON gl_budgets "
        f"USING ({predicate}) WITH CHECK ({predicate})"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON gl_budgets")
    op.drop_constraint('fk_ar_invoice_income_cc', 'ar_invoices', type_='foreignkey')
    op.drop_column('ar_invoices', 'gl_je_header_id')
    op.drop_column('ar_invoices', 'income_combination_id')
    op.drop_column('ar_invoices', 'fund')
    op.drop_index(op.f('ix_gl_budgets_tenant_id'), table_name='gl_budgets')
    op.drop_index(op.f('ix_gl_budgets_fund_value'), table_name='gl_budgets')
    op.drop_index(op.f('ix_gl_budgets_code_combination_id'), table_name='gl_budgets')
    op.drop_table('gl_budgets')
