"""resident portal logins + unit links

Revision ID: 85a50392782c
Revises: 7a4ca8e99a04
Create Date: 2026-06-20 14:54:03.609605
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.crypto_types


revision: str = '85a50392782c'
down_revision: Union[str, None] = '7a4ca8e99a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('resident_type', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', app.core.crypto_types.EncryptedString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_resident_username')
    )
    op.create_index(op.f('ix_residents_tenant_id'), 'residents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_residents_username'), 'residents', ['username'], unique=False)
    op.create_table('resident_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=False),
    sa.Column('homeowner_id', sa.UUID(), nullable=False),
    sa.Column('unit_number', sa.String(length=40), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['homeowner_id'], ['ar_homeowners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'unit_number', 'resident_id', name='uq_resident_unit')
    )
    op.create_index(op.f('ix_resident_units_homeowner_id'), 'resident_units', ['homeowner_id'], unique=False)
    op.create_index(op.f('ix_resident_units_resident_id'), 'resident_units', ['resident_id'], unique=False)
    op.create_index(op.f('ix_resident_units_tenant_id'), 'resident_units', ['tenant_id'], unique=False)
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations (not the ORM),
    # so autogenerate mis-flags them as removable. Do NOT drop them.

    # RLS for the new tenant-scoped tables.
    predicate = (
        "current_setting('app.is_superadmin', true) = 'on' "
        "OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    )
    for table in ("residents", "resident_units"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({predicate}) WITH CHECK ({predicate})"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON resident_units")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON residents")
    op.drop_index(op.f('ix_resident_units_tenant_id'), table_name='resident_units')
    op.drop_index(op.f('ix_resident_units_resident_id'), table_name='resident_units')
    op.drop_index(op.f('ix_resident_units_homeowner_id'), table_name='resident_units')
    op.drop_table('resident_units')
    op.drop_index(op.f('ix_residents_username'), table_name='residents')
    op.drop_index(op.f('ix_residents_tenant_id'), table_name='residents')
    op.drop_table('residents')
    # ### end Alembic commands ###
