"""dunning rules logs and dunning_enabled

Revision ID: 8f7a60f004e5
Revises: 0707b76bd5f2
Create Date: 2026-06-23 08:34:15.593702
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8f7a60f004e5'
down_revision: Union[str, None] = '0707b76bd5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dunning_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('days_past_due', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('action', sa.String(length=12), nullable=False),
    sa.Column('escalate_to_stage', sa.String(length=20), nullable=True),
    sa.Column('attach_statement', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dunning_rules_tenant_id'), 'dunning_rules', ['tenant_id'], unique=False)
    op.create_table('dunning_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('homeowner_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('days_past_due', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('action', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['homeowner_id'], ['ar_homeowners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['dunning_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dunning_logs_homeowner_id'), 'dunning_logs', ['homeowner_id'], unique=False)
    op.create_index(op.f('ix_dunning_logs_tenant_id'), 'dunning_logs', ['tenant_id'], unique=False)
    op.add_column('scheduler_config', sa.Column('dunning_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; do NOT drop them.
    predicate = "current_setting('app.is_superadmin', true) = 'on' OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    for table in ('dunning_rules', 'dunning_logs'):
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON {table} '
            f'USING ({predicate}) WITH CHECK ({predicate})'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ('dunning_rules', 'dunning_logs'):
        op.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table}')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler_config', 'dunning_enabled')
    op.drop_index(op.f('ix_dunning_logs_tenant_id'), table_name='dunning_logs')
    op.drop_index(op.f('ix_dunning_logs_homeowner_id'), table_name='dunning_logs')
    op.drop_table('dunning_logs')
    op.drop_index(op.f('ix_dunning_rules_tenant_id'), table_name='dunning_rules')
    op.drop_table('dunning_rules')
    # ### end Alembic commands ###
