"""matching link notifications tolerances

Revision ID: 8fbf7cf73a9b
Revises: 782a717dbb64
Create Date: 2026-06-22 00:10:19.941876
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8fbf7cf73a9b'
down_revision: Union[str, None] = '782a717dbb64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ap_match_tolerances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount_tolerance_pct', sa.Numeric(precision=6, scale=3), nullable=False, server_default='0'),
    sa.Column('quantity_tolerance_pct', sa.Numeric(precision=6, scale=3), nullable=False, server_default='0'),
    sa.Column('require_receipt', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ap_match_tolerances_tenant_id'), 'ap_match_tolerances', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('recipient_role_code', sa.String(length=40), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_recipient_role_code'), 'notifications', ['recipient_role_code'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.add_column('ap_invoice_distributions', sa.Column('po_distribution_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_ap_invoice_distributions_po_distribution_id'), 'ap_invoice_distributions', ['po_distribution_id'], unique=False)
    op.create_foreign_key(None, 'ap_invoice_distributions', 'po_distributions', ['po_distribution_id'], ['id'], ondelete='SET NULL')
    predicate = ("current_setting('app.is_superadmin', true) = 'on' "
                 "OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid")
    for table in ("notifications", "ap_match_tolerances"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"CREATE POLICY tenant_isolation ON {table} USING ({predicate}) WITH CHECK ({predicate})")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ap_invoice_distributions', type_='foreignkey')
    op.drop_index(op.f('ix_ap_invoice_distributions_po_distribution_id'), table_name='ap_invoice_distributions')
    op.drop_column('ap_invoice_distributions', 'po_distribution_id')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_role_code'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_ap_match_tolerances_tenant_id'), table_name='ap_match_tolerances')
    op.drop_table('ap_match_tolerances')
    # ### end Alembic commands ###
