"""financials: po ap ar receipts banks gl batches approvals

Revision ID: 9a778d7533f9
Revises: 03284a5df438
Create Date: 2026-06-20 03:51:53.170396
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.crypto_types


revision: str = '9a778d7533f9'
down_revision: Union[str, None] = '03284a5df438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ap_banks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=False),
    sa.Column('routing_number', sa.String(length=9), nullable=False),
    sa.Column('branch_name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'routing_number', name='uq_bank_routing')
    )
    op.create_index(op.f('ix_ap_banks_routing_number'), 'ap_banks', ['routing_number'], unique=False)
    op.create_index(op.f('ix_ap_banks_tenant_id'), 'ap_banks', ['tenant_id'], unique=False)
    op.create_table('ap_suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_number', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tax_id', app.core.crypto_types.EncryptedString(length=255), nullable=True),
    sa.Column('payment_terms', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'vendor_number', name='uq_supplier_number')
    )
    op.create_index(op.f('ix_ap_suppliers_tenant_id'), 'ap_suppliers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ap_suppliers_vendor_number'), 'ap_suppliers', ['vendor_number'], unique=False)
    op.create_table('approval_hierarchies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'document_type', name='uq_hierarchy_doctype')
    )
    op.create_index(op.f('ix_approval_hierarchies_tenant_id'), 'approval_hierarchies', ['tenant_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('required_levels', sa.Integer(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'document_type', 'document_id', name='uq_request_doc')
    )
    op.create_index(op.f('ix_approval_requests_document_id'), 'approval_requests', ['document_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_document_type'), 'approval_requests', ['document_type'], unique=False)
    op.create_index(op.f('ix_approval_requests_tenant_id'), 'approval_requests', ['tenant_id'], unique=False)
    op.create_table('fnd_lookups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lookup_type', sa.String(length=60), nullable=False),
    sa.Column('lookup_code', sa.String(length=60), nullable=False),
    sa.Column('meaning', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'lookup_type', 'lookup_code', name='uq_lookup')
    )
    op.create_index(op.f('ix_fnd_lookups_lookup_type'), 'fnd_lookups', ['lookup_type'], unique=False)
    op.create_index(op.f('ix_fnd_lookups_tenant_id'), 'fnd_lookups', ['tenant_id'], unique=False)
    op.create_table('gl_je_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('accounting_date', sa.Date(), nullable=False),
    sa.Column('period_name', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('control_total_dr', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('control_total_cr', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'batch_name', name='uq_je_batch_name')
    )
    op.create_index(op.f('ix_gl_je_batches_tenant_id'), 'gl_je_batches', ['tenant_id'], unique=False)
    op.create_index('ix_je_batch_status', 'gl_je_batches', ['tenant_id', 'status'], unique=False)
    op.create_table('approval_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('level_num', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=15), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('acted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_actions_request_id'), 'approval_actions', ['request_id'], unique=False)
    op.create_index(op.f('ix_approval_actions_tenant_id'), 'approval_actions', ['tenant_id'], unique=False)
    op.create_table('approval_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hierarchy_id', sa.UUID(), nullable=False),
    sa.Column('level_num', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('approver_role_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approver_role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hierarchy_id'], ['approval_hierarchies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hierarchy_id', 'level_num', name='uq_rule_level')
    )
    op.create_index(op.f('ix_approval_rules_hierarchy_id'), 'approval_rules', ['hierarchy_id'], unique=False)
    op.create_index(op.f('ix_approval_rules_tenant_id'), 'approval_rules', ['tenant_id'], unique=False)
    op.create_table('gl_je_headers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.UUID(), nullable=False),
    sa.Column('je_name', sa.String(length=100), nullable=False),
    sa.Column('je_category', sa.String(length=30), nullable=False),
    sa.Column('je_source', sa.String(length=20), nullable=False),
    sa.Column('accounting_date', sa.Date(), nullable=False),
    sa.Column('period_name', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('source_doc_type', sa.String(length=20), nullable=True),
    sa.Column('source_doc_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['gl_je_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['structure_id'], ['kff_structures.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gl_je_headers_batch_id'), 'gl_je_headers', ['batch_id'], unique=False)
    op.create_index(op.f('ix_gl_je_headers_source_doc_id'), 'gl_je_headers', ['source_doc_id'], unique=False)
    op.create_index(op.f('ix_gl_je_headers_tenant_id'), 'gl_je_headers', ['tenant_id'], unique=False)
    op.create_table('po_headers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(length=40), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['ap_suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'po_number', name='uq_po_number')
    )
    op.create_index(op.f('ix_po_headers_po_number'), 'po_headers', ['po_number'], unique=False)
    op.create_index(op.f('ix_po_headers_tenant_id'), 'po_headers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_po_headers_vendor_id'), 'po_headers', ['vendor_id'], unique=False)
    op.create_table('ap_bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=False),
    sa.Column('account_number', app.core.crypto_types.EncryptedString(length=255), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('cash_combination_id', sa.UUID(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['ap_banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cash_combination_id'], ['gl_code_combinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ap_bank_accounts_bank_id'), 'ap_bank_accounts', ['bank_id'], unique=False)
    op.create_index(op.f('ix_ap_bank_accounts_tenant_id'), 'ap_bank_accounts', ['tenant_id'], unique=False)
    op.create_table('ap_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('po_header_id', sa.UUID(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('gl_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('invoice_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gl_je_header_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['po_header_id'], ['po_headers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['ap_suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'vendor_id', 'invoice_number', name='uq_ap_invoice_number')
    )
    op.create_index(op.f('ix_ap_invoices_invoice_number'), 'ap_invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_ap_invoices_po_header_id'), 'ap_invoices', ['po_header_id'], unique=False)
    op.create_index(op.f('ix_ap_invoices_tenant_id'), 'ap_invoices', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ap_invoices_vendor_id'), 'ap_invoices', ['vendor_id'], unique=False)
    op.create_table('gl_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_combination_id', sa.UUID(), nullable=False),
    sa.Column('period_name', sa.String(length=15), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_num', sa.Integer(), nullable=False),
    sa.Column('fund_value', sa.String(length=60), nullable=True),
    sa.Column('begin_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('period_net_dr', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('period_net_cr', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['code_combination_id'], ['gl_code_combinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code_combination_id', 'period_name', name='uq_gl_balance')
    )
    op.create_index('ix_gl_balance_fund', 'gl_balances', ['tenant_id', 'fund_value', 'period_name'], unique=False)
    op.create_index(op.f('ix_gl_balances_code_combination_id'), 'gl_balances', ['code_combination_id'], unique=False)
    op.create_index(op.f('ix_gl_balances_fund_value'), 'gl_balances', ['fund_value'], unique=False)
    op.create_index(op.f('ix_gl_balances_tenant_id'), 'gl_balances', ['tenant_id'], unique=False)
    op.create_table('gl_je_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('header_id', sa.UUID(), nullable=False),
    sa.Column('line_num', sa.Integer(), nullable=False),
    sa.Column('code_combination_id', sa.UUID(), nullable=False),
    sa.Column('entered_dr', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('entered_cr', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fund_value', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['code_combination_id'], ['gl_code_combinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['header_id'], ['gl_je_headers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('header_id', 'line_num', name='uq_je_line_num')
    )
    op.create_index(op.f('ix_gl_je_lines_code_combination_id'), 'gl_je_lines', ['code_combination_id'], unique=False)
    op.create_index(op.f('ix_gl_je_lines_fund_value'), 'gl_je_lines', ['fund_value'], unique=False)
    op.create_index(op.f('ix_gl_je_lines_header_id'), 'gl_je_lines', ['header_id'], unique=False)
    op.create_index(op.f('ix_gl_je_lines_tenant_id'), 'gl_je_lines', ['tenant_id'], unique=False)
    op.create_table('po_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_header_id', sa.UUID(), nullable=False),
    sa.Column('line_num', sa.Integer(), nullable=False),
    sa.Column('item_description', sa.String(length=240), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['po_header_id'], ['po_headers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_header_id', 'line_num', name='uq_po_line_num')
    )
    op.create_index(op.f('ix_po_lines_po_header_id'), 'po_lines', ['po_header_id'], unique=False)
    op.create_index(op.f('ix_po_lines_tenant_id'), 'po_lines', ['tenant_id'], unique=False)
    op.create_table('ap_bank_account_uses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=False),
    sa.Column('use_type', sa.String(length=30), nullable=False),
    sa.Column('primary_flag', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['ap_bank_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ap_bank_account_uses_bank_account_id'), 'ap_bank_account_uses', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_ap_bank_account_uses_tenant_id'), 'ap_bank_account_uses', ['tenant_id'], unique=False)
    op.create_table('ap_invoice_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('line_num', sa.Integer(), nullable=False),
    sa.Column('po_line_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['ap_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_lines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'line_num', name='uq_ap_line_num')
    )
    op.create_index(op.f('ix_ap_invoice_lines_invoice_id'), 'ap_invoice_lines', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_ap_invoice_lines_tenant_id'), 'ap_invoice_lines', ['tenant_id'], unique=False)
    op.create_table('ar_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('homeowner_id', sa.UUID(), nullable=False),
    sa.Column('applied_invoice_id', sa.UUID(), nullable=True),
    sa.Column('receipt_number', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('gl_journal_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['applied_invoice_id'], ['ar_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gl_journal_id'], ['gl_journals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['homeowner_id'], ['ar_homeowners.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ar_receipts_homeowner_id'), 'ar_receipts', ['homeowner_id'], unique=False)
    op.create_index(op.f('ix_ar_receipts_tenant_id'), 'ar_receipts', ['tenant_id'], unique=False)
    op.create_table('po_distributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_line_id', sa.UUID(), nullable=False),
    sa.Column('distribution_num', sa.Integer(), nullable=False),
    sa.Column('code_combination_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fund_value', sa.String(length=60), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['code_combination_id'], ['gl_code_combinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_distributions_code_combination_id'), 'po_distributions', ['code_combination_id'], unique=False)
    op.create_index(op.f('ix_po_distributions_fund_value'), 'po_distributions', ['fund_value'], unique=False)
    op.create_index(op.f('ix_po_distributions_po_line_id'), 'po_distributions', ['po_line_id'], unique=False)
    op.create_index(op.f('ix_po_distributions_tenant_id'), 'po_distributions', ['tenant_id'], unique=False)
    op.create_table('ap_invoice_distributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_line_id', sa.UUID(), nullable=False),
    sa.Column('distribution_num', sa.Integer(), nullable=False),
    sa.Column('code_combination_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fund_value', sa.String(length=60), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['code_combination_id'], ['gl_code_combinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['ap_invoice_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ap_invoice_distributions_code_combination_id'), 'ap_invoice_distributions', ['code_combination_id'], unique=False)
    op.create_index(op.f('ix_ap_invoice_distributions_fund_value'), 'ap_invoice_distributions', ['fund_value'], unique=False)
    op.create_index(op.f('ix_ap_invoice_distributions_invoice_line_id'), 'ap_invoice_distributions', ['invoice_line_id'], unique=False)
    op.create_index(op.f('ix_ap_invoice_distributions_tenant_id'), 'ap_invoice_distributions', ['tenant_id'], unique=False)
    # server_default backfills existing ar_invoices rows; the ORM still supplies
    # the value on new inserts, so the DB default is harmless going forward.
    op.add_column('ar_invoices', sa.Column('invoice_type', sa.String(length=20), nullable=False, server_default='ASSESSMENT'))
    op.add_column('ar_invoices', sa.Column('amount_paid', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###

    # Row-Level Security for all new tenant-scoped tables. Grants are inherited
    # via the ALTER DEFAULT PRIVILEGES set in revision a1b2c3d4e5f6.
    predicate = (
        "current_setting('app.is_superadmin', true) = 'on' "
        "OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    )
    for table in (
        "fnd_lookups", "ap_suppliers", "ap_banks", "ap_bank_accounts",
        "ap_bank_account_uses", "po_headers", "po_lines", "po_distributions",
        "ap_invoices", "ap_invoice_lines", "ap_invoice_distributions",
        "ar_receipts", "gl_je_batches", "gl_je_headers", "gl_je_lines",
        "gl_balances", "approval_hierarchies", "approval_rules",
        "approval_requests", "approval_actions",
    ):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({predicate}) WITH CHECK ({predicate})"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ar_invoices', 'amount_paid')
    op.drop_column('ar_invoices', 'invoice_type')
    op.drop_index(op.f('ix_ap_invoice_distributions_tenant_id'), table_name='ap_invoice_distributions')
    op.drop_index(op.f('ix_ap_invoice_distributions_invoice_line_id'), table_name='ap_invoice_distributions')
    op.drop_index(op.f('ix_ap_invoice_distributions_fund_value'), table_name='ap_invoice_distributions')
    op.drop_index(op.f('ix_ap_invoice_distributions_code_combination_id'), table_name='ap_invoice_distributions')
    op.drop_table('ap_invoice_distributions')
    op.drop_index(op.f('ix_po_distributions_tenant_id'), table_name='po_distributions')
    op.drop_index(op.f('ix_po_distributions_po_line_id'), table_name='po_distributions')
    op.drop_index(op.f('ix_po_distributions_fund_value'), table_name='po_distributions')
    op.drop_index(op.f('ix_po_distributions_code_combination_id'), table_name='po_distributions')
    op.drop_table('po_distributions')
    op.drop_index(op.f('ix_ar_receipts_tenant_id'), table_name='ar_receipts')
    op.drop_index(op.f('ix_ar_receipts_homeowner_id'), table_name='ar_receipts')
    op.drop_table('ar_receipts')
    op.drop_index(op.f('ix_ap_invoice_lines_tenant_id'), table_name='ap_invoice_lines')
    op.drop_index(op.f('ix_ap_invoice_lines_invoice_id'), table_name='ap_invoice_lines')
    op.drop_table('ap_invoice_lines')
    op.drop_index(op.f('ix_ap_bank_account_uses_tenant_id'), table_name='ap_bank_account_uses')
    op.drop_index(op.f('ix_ap_bank_account_uses_bank_account_id'), table_name='ap_bank_account_uses')
    op.drop_table('ap_bank_account_uses')
    op.drop_index(op.f('ix_po_lines_tenant_id'), table_name='po_lines')
    op.drop_index(op.f('ix_po_lines_po_header_id'), table_name='po_lines')
    op.drop_table('po_lines')
    op.drop_index(op.f('ix_gl_je_lines_tenant_id'), table_name='gl_je_lines')
    op.drop_index(op.f('ix_gl_je_lines_header_id'), table_name='gl_je_lines')
    op.drop_index(op.f('ix_gl_je_lines_fund_value'), table_name='gl_je_lines')
    op.drop_index(op.f('ix_gl_je_lines_code_combination_id'), table_name='gl_je_lines')
    op.drop_table('gl_je_lines')
    op.drop_index(op.f('ix_gl_balances_tenant_id'), table_name='gl_balances')
    op.drop_index(op.f('ix_gl_balances_fund_value'), table_name='gl_balances')
    op.drop_index(op.f('ix_gl_balances_code_combination_id'), table_name='gl_balances')
    op.drop_index('ix_gl_balance_fund', table_name='gl_balances')
    op.drop_table('gl_balances')
    op.drop_index(op.f('ix_ap_invoices_vendor_id'), table_name='ap_invoices')
    op.drop_index(op.f('ix_ap_invoices_tenant_id'), table_name='ap_invoices')
    op.drop_index(op.f('ix_ap_invoices_po_header_id'), table_name='ap_invoices')
    op.drop_index(op.f('ix_ap_invoices_invoice_number'), table_name='ap_invoices')
    op.drop_table('ap_invoices')
    op.drop_index(op.f('ix_ap_bank_accounts_tenant_id'), table_name='ap_bank_accounts')
    op.drop_index(op.f('ix_ap_bank_accounts_bank_id'), table_name='ap_bank_accounts')
    op.drop_table('ap_bank_accounts')
    op.drop_index(op.f('ix_po_headers_vendor_id'), table_name='po_headers')
    op.drop_index(op.f('ix_po_headers_tenant_id'), table_name='po_headers')
    op.drop_index(op.f('ix_po_headers_po_number'), table_name='po_headers')
    op.drop_table('po_headers')
    op.drop_index(op.f('ix_gl_je_headers_tenant_id'), table_name='gl_je_headers')
    op.drop_index(op.f('ix_gl_je_headers_source_doc_id'), table_name='gl_je_headers')
    op.drop_index(op.f('ix_gl_je_headers_batch_id'), table_name='gl_je_headers')
    op.drop_table('gl_je_headers')
    op.drop_index(op.f('ix_approval_rules_tenant_id'), table_name='approval_rules')
    op.drop_index(op.f('ix_approval_rules_hierarchy_id'), table_name='approval_rules')
    op.drop_table('approval_rules')
    op.drop_index(op.f('ix_approval_actions_tenant_id'), table_name='approval_actions')
    op.drop_index(op.f('ix_approval_actions_request_id'), table_name='approval_actions')
    op.drop_table('approval_actions')
    op.drop_index('ix_je_batch_status', table_name='gl_je_batches')
    op.drop_index(op.f('ix_gl_je_batches_tenant_id'), table_name='gl_je_batches')
    op.drop_table('gl_je_batches')
    op.drop_index(op.f('ix_fnd_lookups_tenant_id'), table_name='fnd_lookups')
    op.drop_index(op.f('ix_fnd_lookups_lookup_type'), table_name='fnd_lookups')
    op.drop_table('fnd_lookups')
    op.drop_index(op.f('ix_approval_requests_tenant_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_document_type'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_document_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_approval_hierarchies_tenant_id'), table_name='approval_hierarchies')
    op.drop_table('approval_hierarchies')
    op.drop_index(op.f('ix_ap_suppliers_vendor_number'), table_name='ap_suppliers')
    op.drop_index(op.f('ix_ap_suppliers_tenant_id'), table_name='ap_suppliers')
    op.drop_table('ap_suppliers')
    op.drop_index(op.f('ix_ap_banks_tenant_id'), table_name='ap_banks')
    op.drop_index(op.f('ix_ap_banks_routing_number'), table_name='ap_banks')
    op.drop_table('ap_banks')
    # ### end Alembic commands ###
