"""service desk tickets

Revision ID: c6a4544d0bed
Revises: 9a778d7533f9
Create Date: 2026-06-20 04:34:56.734652
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c6a4544d0bed'
down_revision: Union[str, None] = '9a778d7533f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_number', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('homeowner_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('po_header_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['homeowner_id'], ['ar_homeowners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['po_header_id'], ['po_headers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['ap_suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'ticket_number', name='uq_ticket_number')
    )
    op.create_index(op.f('ix_service_tickets_tenant_id'), 'service_tickets', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_service_tickets_ticket_number'), 'service_tickets', ['ticket_number'], unique=False)
    # ### end Alembic commands ###

    predicate = (
        "current_setting('app.is_superadmin', true) = 'on' "
        "OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    )
    op.execute("ALTER TABLE service_tickets ENABLE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON service_tickets "
        f"USING ({predicate}) WITH CHECK ({predicate})"
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON service_tickets")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_tickets_ticket_number'), table_name='service_tickets')
    op.drop_index(op.f('ix_service_tickets_tenant_id'), table_name='service_tickets')
    op.drop_table('service_tickets')
    # ### end Alembic commands ###
