"""accounting periods

Revision ID: e1fe524c1ec7
Revises: fc7aec628496
Create Date: 2026-06-22 18:28:47.412414
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e1fe524c1ec7'
down_revision: Union[str, None] = 'fc7aec628496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_name', sa.String(length=15), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_num', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'period_name', name='uq_accounting_period')
    )
    op.create_index(op.f('ix_accounting_periods_period_name'), 'accounting_periods', ['period_name'], unique=False)
    op.create_index(op.f('ix_accounting_periods_tenant_id'), 'accounting_periods', ['tenant_id'], unique=False)
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; do NOT drop them.
    predicate = "current_setting('app.is_superadmin', true) = 'on' OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    op.execute('ALTER TABLE accounting_periods ENABLE ROW LEVEL SECURITY')
    op.execute(
        f'CREATE POLICY tenant_isolation ON accounting_periods '
        f'USING ({predicate}) WITH CHECK ({predicate})'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute('DROP POLICY IF EXISTS tenant_isolation ON accounting_periods')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounting_periods_tenant_id'), table_name='accounting_periods')
    op.drop_index(op.f('ix_accounting_periods_period_name'), table_name='accounting_periods')
    op.drop_table('accounting_periods')
    # ### end Alembic commands ###
