"""ar billing plans late fees documents

Revision ID: efdfaa831b70
Revises: 754239dd12bf
Create Date: 2026-06-22 19:56:35.452983
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'efdfaa831b70'
down_revision: Union[str, None] = '754239dd12bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_billing_plan_name')
    )
    op.create_index(op.f('ix_billing_plans_tenant_id'), 'billing_plans', ['tenant_id'], unique=False)
    op.create_table('document_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('storage_key', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('homeowner_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_attachments_entity_id'), 'document_attachments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_document_attachments_entity_type'), 'document_attachments', ['entity_type'], unique=False)
    op.create_index(op.f('ix_document_attachments_homeowner_id'), 'document_attachments', ['homeowner_id'], unique=False)
    op.create_index(op.f('ix_document_attachments_tenant_id'), 'document_attachments', ['tenant_id'], unique=False)
    op.create_table('billing_plan_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('income_combination_id', sa.UUID(), nullable=False),
    sa.Column('fund_value', sa.String(length=60), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['income_combination_id'], ['gl_code_combinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['billing_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_plan_lines_plan_id'), 'billing_plan_lines', ['plan_id'], unique=False)
    op.create_index(op.f('ix_billing_plan_lines_tenant_id'), 'billing_plan_lines', ['tenant_id'], unique=False)
    op.create_table('late_fee_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('grace_days', sa.Integer(), nullable=False),
    sa.Column('fee_type', sa.String(length=10), nullable=False),
    sa.Column('flat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('fund_value', sa.String(length=60), nullable=False),
    sa.Column('income_combination_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['income_combination_id'], ['gl_code_combinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_late_fee_rules_tenant_id'), 'late_fee_rules', ['tenant_id'], unique=False)
    op.add_column('ar_invoices', sa.Column('late_fee_applied', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; do NOT drop them.
    predicate = "current_setting('app.is_superadmin', true) = 'on' OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    for table in ('billing_plans', 'billing_plan_lines', 'late_fee_rules', 'document_attachments'):
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON {table} '
            f'USING ({predicate}) WITH CHECK ({predicate})'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ('billing_plans', 'billing_plan_lines', 'late_fee_rules', 'document_attachments'):
        op.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table}')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ar_invoices', 'late_fee_applied')
    op.drop_index(op.f('ix_late_fee_rules_tenant_id'), table_name='late_fee_rules')
    op.drop_table('late_fee_rules')
    op.drop_index(op.f('ix_billing_plan_lines_tenant_id'), table_name='billing_plan_lines')
    op.drop_index(op.f('ix_billing_plan_lines_plan_id'), table_name='billing_plan_lines')
    op.drop_table('billing_plan_lines')
    op.drop_index(op.f('ix_document_attachments_tenant_id'), table_name='document_attachments')
    op.drop_index(op.f('ix_document_attachments_homeowner_id'), table_name='document_attachments')
    op.drop_index(op.f('ix_document_attachments_entity_type'), table_name='document_attachments')
    op.drop_index(op.f('ix_document_attachments_entity_id'), table_name='document_attachments')
    op.drop_table('document_attachments')
    op.drop_index(op.f('ix_billing_plans_tenant_id'), table_name='billing_plans')
    op.drop_table('billing_plans')
    # ### end Alembic commands ###
