"""budget versions lines control

Revision ID: f472d9cbb2bb
Revises: e1fe524c1ec7
Create Date: 2026-06-22 18:54:05.745105
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f472d9cbb2bb'
down_revision: Union[str, None] = 'e1fe524c1ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('version_type', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('is_controlling', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_budget_version_name')
    )
    op.create_index(op.f('ix_budget_versions_tenant_id'), 'budget_versions', ['tenant_id'], unique=False)
    op.create_table('budget_control_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('controlling_version_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['controlling_version_id'], ['budget_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_control_settings_tenant_id'), 'budget_control_settings', ['tenant_id'], unique=False)
    op.create_table('budget_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('code_combination_id', sa.UUID(), nullable=False),
    sa.Column('fund_value', sa.String(length=60), nullable=False),
    sa.Column('cost_center_value', sa.String(length=60), nullable=True),
    sa.Column('period_num', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['code_combination_id'], ['gl_code_combinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['budget_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'code_combination_id', 'period_num', name='uq_budget_line')
    )
    op.create_index(op.f('ix_budget_lines_code_combination_id'), 'budget_lines', ['code_combination_id'], unique=False)
    op.create_index(op.f('ix_budget_lines_fund_value'), 'budget_lines', ['fund_value'], unique=False)
    op.create_index(op.f('ix_budget_lines_tenant_id'), 'budget_lines', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_budget_lines_version_id'), 'budget_lines', ['version_id'], unique=False)
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; do NOT drop them.
    predicate = "current_setting('app.is_superadmin', true) = 'on' OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    for table in ('budget_versions', 'budget_lines', 'budget_control_settings'):
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON {table} '
            f'USING ({predicate}) WITH CHECK ({predicate})'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ('budget_versions', 'budget_lines', 'budget_control_settings'):
        op.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table}')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_lines_version_id'), table_name='budget_lines')
    op.drop_index(op.f('ix_budget_lines_tenant_id'), table_name='budget_lines')
    op.drop_index(op.f('ix_budget_lines_fund_value'), table_name='budget_lines')
    op.drop_index(op.f('ix_budget_lines_code_combination_id'), table_name='budget_lines')
    op.drop_table('budget_lines')
    op.drop_index(op.f('ix_budget_control_settings_tenant_id'), table_name='budget_control_settings')
    op.drop_table('budget_control_settings')
    op.drop_index(op.f('ix_budget_versions_tenant_id'), table_name='budget_versions')
    op.drop_table('budget_versions')
    # ### end Alembic commands ###
