"""statement runs deliveries and opt out

Revision ID: f8181bb3a884
Revises: 22933f00c427
Create Date: 2026-06-23 00:37:15.316321
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8181bb3a884'
down_revision: Union[str, None] = '22933f00c427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statement_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_number', sa.String(length=40), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('generated', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('sent', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('skipped', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('failed', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_runs_run_number'), 'statement_runs', ['run_number'], unique=False)
    op.create_index(op.f('ix_statement_runs_tenant_id'), 'statement_runs', ['tenant_id'], unique=False)
    op.create_table('statement_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('homeowner_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['homeowner_id'], ['ar_homeowners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['statement_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_deliveries_homeowner_id'), 'statement_deliveries', ['homeowner_id'], unique=False)
    op.create_index(op.f('ix_statement_deliveries_run_id'), 'statement_deliveries', ['run_id'], unique=False)
    op.create_index(op.f('ix_statement_deliveries_tenant_id'), 'statement_deliveries', ['tenant_id'], unique=False)
    op.add_column('ar_homeowners', sa.Column('statement_opt_out', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; do NOT drop them.
    predicate = "current_setting('app.is_superadmin', true) = 'on' OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    for table in ('statement_runs', 'statement_deliveries'):
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON {table} '
            f'USING ({predicate}) WITH CHECK ({predicate})'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ('statement_runs', 'statement_deliveries'):
        op.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table}')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ar_homeowners', 'statement_opt_out')
    op.drop_index(op.f('ix_statement_deliveries_tenant_id'), table_name='statement_deliveries')
    op.drop_index(op.f('ix_statement_deliveries_run_id'), table_name='statement_deliveries')
    op.drop_index(op.f('ix_statement_deliveries_homeowner_id'), table_name='statement_deliveries')
    op.drop_table('statement_deliveries')
    op.drop_index(op.f('ix_statement_runs_tenant_id'), table_name='statement_runs')
    op.drop_index(op.f('ix_statement_runs_run_number'), table_name='statement_runs')
    op.drop_table('statement_runs')
    # ### end Alembic commands ###
