"""encumbrance settings and po encumbrances

Revision ID: fc7aec628496
Revises: 168904d0f49c
Create Date: 2026-06-22 12:27:29.843137
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc7aec628496'
down_revision: Union[str, None] = '168904d0f49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encumbrance_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('encumbrance_combination_id', sa.UUID(), nullable=True),
    sa.Column('reserve_combination_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['encumbrance_combination_id'], ['gl_code_combinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reserve_combination_id'], ['gl_code_combinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encumbrance_settings_tenant_id'), 'encumbrance_settings', ['tenant_id'], unique=False)
    op.create_table('po_encumbrances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_header_id', sa.UUID(), nullable=False),
    sa.Column('encumbered_amount', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'),
    sa.Column('liquidated_amount', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('je_header_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['po_header_id'], ['po_headers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'po_header_id', name='uq_po_encumbrance')
    )
    op.create_index(op.f('ix_po_encumbrances_po_header_id'), 'po_encumbrances', ['po_header_id'], unique=False)
    op.create_index(op.f('ix_po_encumbrances_tenant_id'), 'po_encumbrances', ['tenant_id'], unique=False)
    # NOTE: perf indexes from d7b1f0c2a9e1 live only in migrations; do NOT drop them.
    predicate = "current_setting('app.is_superadmin', true) = 'on' OR tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    for table in ('encumbrance_settings', 'po_encumbrances'):
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON {table} '
            f'USING ({predicate}) WITH CHECK ({predicate})'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ('encumbrance_settings', 'po_encumbrances'):
        op.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table}')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_po_encumbrances_tenant_id'), table_name='po_encumbrances')
    op.drop_index(op.f('ix_po_encumbrances_po_header_id'), table_name='po_encumbrances')
    op.drop_table('po_encumbrances')
    op.drop_index(op.f('ix_encumbrance_settings_tenant_id'), table_name='encumbrance_settings')
    op.drop_table('encumbrance_settings')
    # ### end Alembic commands ###
