"""initial schema

Revision ID: fd9d0e868ac5
Revises: 
Create Date: 2026-06-20 02:26:45.977862
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fd9d0e868ac5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('num_units', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('functional_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('kff_structures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structure_code', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('segment_separator', sa.String(length=1), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_coa', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'structure_code', name='uq_kff_structure_code')
    )
    op.create_index(op.f('ix_kff_structures_tenant_id'), 'kff_structures', ['tenant_id'], unique=False)
    op.create_table('kff_value_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('validation_type', sa.String(length=20), nullable=False),
    sa.Column('format_type', sa.String(length=10), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=False),
    sa.Column('uppercase_only', sa.Boolean(), nullable=False),
    sa.Column('zero_fill', sa.Boolean(), nullable=False),
    sa.Column('numbers_only', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_value_set_code')
    )
    op.create_index(op.f('ix_kff_value_sets_tenant_id'), 'kff_value_sets', ['tenant_id'], unique=False)
    op.create_table('payment_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('homeowner_id', sa.UUID(), nullable=True),
    sa.Column('vault_token', sa.String(length=255), nullable=False),
    sa.Column('card_brand', sa.String(length=20), nullable=True),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('exp_month', sa.Integer(), nullable=True),
    sa.Column('exp_year', sa.Integer(), nullable=True),
    sa.Column('holder_name', sa.String(length=120), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_tokens_homeowner_id'), 'payment_tokens', ['homeowner_id'], unique=False)
    op.create_index(op.f('ix_payment_tokens_tenant_id'), 'payment_tokens', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_role_tenant_code')
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('gl_code_combinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.UUID(), nullable=False),
    sa.Column('concatenated_segments', sa.String(length=800), nullable=False),
    sa.Column('balancing_segment_value', sa.String(length=60), nullable=True),
    sa.Column('natural_account_value', sa.String(length=60), nullable=True),
    sa.Column('cost_center_value', sa.String(length=60), nullable=True),
    sa.Column('fund_value', sa.String(length=60), nullable=True),
    sa.Column('account_type', sa.String(length=1), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('allow_posting', sa.Boolean(), nullable=False),
    sa.Column('summary_flag', sa.Boolean(), nullable=False),
    sa.Column('start_date_active', sa.Date(), nullable=True),
    sa.Column('end_date_active', sa.Date(), nullable=True),
    sa.Column('segment1', sa.String(length=60), nullable=True),
    sa.Column('segment2', sa.String(length=60), nullable=True),
    sa.Column('segment3', sa.String(length=60), nullable=True),
    sa.Column('segment4', sa.String(length=60), nullable=True),
    sa.Column('segment5', sa.String(length=60), nullable=True),
    sa.Column('segment6', sa.String(length=60), nullable=True),
    sa.Column('segment7', sa.String(length=60), nullable=True),
    sa.Column('segment8', sa.String(length=60), nullable=True),
    sa.Column('segment9', sa.String(length=60), nullable=True),
    sa.Column('segment10', sa.String(length=60), nullable=True),
    sa.Column('segment11', sa.String(length=60), nullable=True),
    sa.Column('segment12', sa.String(length=60), nullable=True),
    sa.Column('segment13', sa.String(length=60), nullable=True),
    sa.Column('segment14', sa.String(length=60), nullable=True),
    sa.Column('segment15', sa.String(length=60), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['structure_id'], ['kff_structures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_id', 'concatenated_segments', name='uq_ccid_concat')
    )
    op.create_index(op.f('ix_gl_code_combinations_balancing_segment_value'), 'gl_code_combinations', ['balancing_segment_value'], unique=False)
    op.create_index(op.f('ix_gl_code_combinations_concatenated_segments'), 'gl_code_combinations', ['concatenated_segments'], unique=False)
    op.create_index(op.f('ix_gl_code_combinations_fund_value'), 'gl_code_combinations', ['fund_value'], unique=False)
    op.create_index(op.f('ix_gl_code_combinations_natural_account_value'), 'gl_code_combinations', ['natural_account_value'], unique=False)
    op.create_index(op.f('ix_gl_code_combinations_structure_id'), 'gl_code_combinations', ['structure_id'], unique=False)
    op.create_index(op.f('ix_gl_code_combinations_tenant_id'), 'gl_code_combinations', ['tenant_id'], unique=False)
    op.create_table('kff_cross_validation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=240), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['structure_id'], ['kff_structures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kff_cross_validation_rules_structure_id'), 'kff_cross_validation_rules', ['structure_id'], unique=False)
    op.create_index(op.f('ix_kff_cross_validation_rules_tenant_id'), 'kff_cross_validation_rules', ['tenant_id'], unique=False)
    op.create_table('kff_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.UUID(), nullable=False),
    sa.Column('segment_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prompt', sa.String(length=120), nullable=False),
    sa.Column('column_name', sa.String(length=20), nullable=False),
    sa.Column('value_set_id', sa.UUID(), nullable=True),
    sa.Column('qualifier', sa.String(length=30), nullable=False),
    sa.Column('displayed', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.String(length=60), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['structure_id'], ['kff_structures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['value_set_id'], ['kff_value_sets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_id', 'column_name', name='uq_segment_column'),
    sa.UniqueConstraint('structure_id', 'segment_number', name='uq_segment_number')
    )
    op.create_index(op.f('ix_kff_segments_structure_id'), 'kff_segments', ['structure_id'], unique=False)
    op.create_index(op.f('ix_kff_segments_tenant_id'), 'kff_segments', ['tenant_id'], unique=False)
    op.create_table('kff_value_set_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value_set_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('summary_flag', sa.Boolean(), nullable=False),
    sa.Column('allow_posting', sa.Boolean(), nullable=False),
    sa.Column('parent_value', sa.String(length=60), nullable=True),
    sa.Column('account_type', sa.String(length=1), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['value_set_id'], ['kff_value_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value_set_id', 'value', name='uq_value_set_value')
    )
    op.create_index(op.f('ix_kff_value_set_values_tenant_id'), 'kff_value_set_values', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_kff_value_set_values_value_set_id'), 'kff_value_set_values', ['value_set_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', 'role_id', name='uq_membership')
    )
    op.create_index(op.f('ix_memberships_tenant_id'), 'memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('kff_cross_validation_rule_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('include_exclude', sa.String(length=10), nullable=False),
    sa.Column('segment_number', sa.Integer(), nullable=False),
    sa.Column('low_value', sa.String(length=60), nullable=False),
    sa.Column('high_value', sa.String(length=60), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['kff_cross_validation_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kff_cross_validation_rule_lines_rule_id'), 'kff_cross_validation_rule_lines', ['rule_id'], unique=False)
    op.create_index(op.f('ix_kff_cross_validation_rule_lines_tenant_id'), 'kff_cross_validation_rule_lines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kff_cross_validation_rule_lines_tenant_id'), table_name='kff_cross_validation_rule_lines')
    op.drop_index(op.f('ix_kff_cross_validation_rule_lines_rule_id'), table_name='kff_cross_validation_rule_lines')
    op.drop_table('kff_cross_validation_rule_lines')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_tenant_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_kff_value_set_values_value_set_id'), table_name='kff_value_set_values')
    op.drop_index(op.f('ix_kff_value_set_values_tenant_id'), table_name='kff_value_set_values')
    op.drop_table('kff_value_set_values')
    op.drop_index(op.f('ix_kff_segments_tenant_id'), table_name='kff_segments')
    op.drop_index(op.f('ix_kff_segments_structure_id'), table_name='kff_segments')
    op.drop_table('kff_segments')
    op.drop_index(op.f('ix_kff_cross_validation_rules_tenant_id'), table_name='kff_cross_validation_rules')
    op.drop_index(op.f('ix_kff_cross_validation_rules_structure_id'), table_name='kff_cross_validation_rules')
    op.drop_table('kff_cross_validation_rules')
    op.drop_index(op.f('ix_gl_code_combinations_tenant_id'), table_name='gl_code_combinations')
    op.drop_index(op.f('ix_gl_code_combinations_structure_id'), table_name='gl_code_combinations')
    op.drop_index(op.f('ix_gl_code_combinations_natural_account_value'), table_name='gl_code_combinations')
    op.drop_index(op.f('ix_gl_code_combinations_fund_value'), table_name='gl_code_combinations')
    op.drop_index(op.f('ix_gl_code_combinations_concatenated_segments'), table_name='gl_code_combinations')
    op.drop_index(op.f('ix_gl_code_combinations_balancing_segment_value'), table_name='gl_code_combinations')
    op.drop_table('gl_code_combinations')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_payment_tokens_tenant_id'), table_name='payment_tokens')
    op.drop_index(op.f('ix_payment_tokens_homeowner_id'), table_name='payment_tokens')
    op.drop_table('payment_tokens')
    op.drop_index(op.f('ix_kff_value_sets_tenant_id'), table_name='kff_value_sets')
    op.drop_table('kff_value_sets')
    op.drop_index(op.f('ix_kff_structures_tenant_id'), table_name='kff_structures')
    op.drop_table('kff_structures')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
