"""ap invoice holds and tax

Revision ID: feb391f7b096
Revises: 24a0ec0aefc9
Create Date: 2026-06-21 23:56:04.748495
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'feb391f7b096'
down_revision: Union[str, None] = '24a0ec0aefc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ap_invoices', sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'))
    op.add_column('ap_invoices', sa.Column('on_hold', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('ap_invoices', sa.Column('hold_reason', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ap_invoices', 'hold_reason')
    op.drop_column('ap_invoices', 'on_hold')
    op.drop_column('ap_invoices', 'tax_amount')
    # ### end Alembic commands ###
